export const Items = [
  {
    Picture: require('../src/images/Mama.jpg'),
    Price: 300000,
    NamaAlbum : "MAMA",
    Rilis : "09 April 2012",
    Genre : "R&B, Pop, Dance",
    Bahasa : "Korea, Mandarin",
    Durasi : "21:41",
  },
  {
    Picture: require("../src/images/Xoxo.jpg"),
    Price: 300000,
    NamaAlbum : " XOXO",
    Rilis : "June 3, 2013",
    Genre : "K-Pop, HipHop, Electro-Pop, R&B, Mandapop",
    Bahasa : "Korea, Mandarin",
    Durasi : "43:48",
  },
  {
    Picture: require("../src/images/Growl.jpg"),
    Price: 300000,
    NamaAlbum : "GROWL",
    Rilis : "05 Agustus 2013",
    Genre : "Hip hop, popR&B",
    Bahasa : "Korea, Mandarin",
    Durasi : "3:27",
  },
  {
    Picture: require("../src/images/Miracle.jpg"),
    Price: 300000,
    NamaAlbum : "MIRACLE IN DECEMBER",
    Rilis : "4 December 2013",
    Genre : "K-Pop, balada",
    Bahasa : "Korea, Mandarin",
    Durasi : "4:34",
  },
  {
    Picture: require("../src/images/Overdose.jpg"),
    Price: 300000,
    NamaAlbum : "OVERDOSE",
    Rilis : "7 Mei 2014",
    Genre : " R&B, HipHop, Pop, Dubstep",
    Bahasa : "Korea, Mandarin",
    Durasi : "OVERDOSE",
  },
  {
    Picture: require("../src/images/Exology.jpg"),
    Price: 300000,
    NamaAlbum : "EXOLOGY CHAPTER 1: THE LOST PLANET", 
    Rilis : "22 December 2014",
    Genre : "K-Pop, Electropop, Hip Hop, R&B",
    Bahasa : "Korea, Mandarin",
    Durasi : "54:57",
  },
  {
    Picture: require("../src/images/Exodus.jpg"),
    Price: 300000,
    NamaAlbum : "EXODUS",
    Rilis : "30 Maret 2015",
    Genre : "K-Pop, Dance, R&B",
    Bahasa : "Korea, Mandarin",
    Durasi : "37:14",
  },
  {
    Picture: require("../src/images/LoveMeRight.jpg"),
    Price: 300000,
    NamaAlbum : "LOVE ME RIGHT",
    Rilis : "09 April 2012",
    Genre : "R&B, Pop, Dance",
    Bahasa : "Korea, Mandarin",
    Durasi : "3:25",
  },
  {
    Picture: require("../src/images/SingForYou.jpg"),
    Price: 300000,
    NamaAlbum : "SING FOR YOU",
    Rilis : "10 Desember 2015",
    Genre : " K-Pop, balada",
    Bahasa : "Korea, Mandarin",
    Durasi : "17:07",
  },
  {
    Picture: require("../src/images/Ex'art.jpg"),
    Price: 300000,
    NamaAlbum : "EX'ART",
    Rilis : "9 Juni 2016",
    Genre : "K-Pop, R&B, Acid House",
    Bahasa : "Korea, Mandarin",
    Durasi : "41:19",
  },  
  {
    Picture: require("../src/images/LuckyOne.jpg"),
    Price: 300000,
    NamaAlbum : "LUCKY ONE",
    Rilis : "9 Juni 2016",
    Genre : "K-Pop, R&B, Dance, Pop",
    Bahasa : "Korea, Mandarin",
    Durasi : "3:47",
  },
  {
    Picture: require("../src/images/Lotto.jpg"),
    Price: 300000,
    NamaAlbum : "LOTTO",
    Rilis : "18 Agustus 2016",
    Genre : "K-Pop, Dance",
    Bahasa : "Korea, Mandarin",
    Durasi : "3:10",
  },
  {
    Picture: require("../src/images/ForLife.jpg"),
    Price: 300000,
    NamaAlbum : "FOR LIFE",
    Rilis : "19 Desember 2016",
    Genre : "K-Pop, R&B, balada",
    Bahasa : "Korea, Mandarin",
    Durasi : "17:59",
  },
  {
    Picture: require("../src/images/TheWar.jpg"),
    Price: 300000,
    NamaAlbum : "THE WAR",
    Rilis : " 19 Juli 2017",
    Genre : "K-Pop, Hip Hop, R&B, EDM",
    Bahasa : "Korea, Mandarin",
    Durasi : " 31:35",
  },
  {
    Picture: require("../src/images/Universe.jpg"),
    Price: 300000,
    NamaAlbum : "UNIVERSE",
    Rilis : "26 Desember 2017",
    Genre : "K-Pop, R&B, Ballad",
    Bahasa : "Korea, Mandarin",
    Durasi : "30:45",
  },
  {
    Picture: require("../src/images/Countdown.jpg"),
    Price: 300000,
    NamaAlbum : "COUNTDOWN",
    Rilis : "31 Januari 2018",
    Genre : "J-pop",
    Bahasa : "Japanese",
    Durasi : "36:08",
  },
  {
    Picture: require("../src/images/Dmmt.jpg"),
    Price: 300000,
    NamaAlbum : "DON'T MESS UP MY TEMPO",
    Rilis : "2 November 2018",
    Genre : "K-Pop, Dance",
    Bahasa : "Korea, Mandarin",
    Durasi : "39:10",
  },
  {
    Picture: require("../src/images/LoveShot.jpg"),
    Price: 300000,
    NamaAlbum : "LOVE SHOT",
    Rilis : "13 Desember 2018",
    Genre : "Dance, R&B, Soul",
    Bahasa : "Korea, Mandarin",
    Durasi : "14:30",
  },
  {
    Picture: require("../src/images/Obsession.jpg"),
    Price: 300000,
    NamaAlbum : "OBSESSION",
    Rilis : "27 November 2019",
    Genre : "Dance, R&B, Soul",
    Bahasa : "Korea, Mandarin",
    Durasi : "34:12",
  },
  {
    Picture: require("../src/images/Dftf.jpg"),
    Price: 300000,
    NamaAlbum : "DON'T FIGHT THE FEELING",
    Rilis : "7 Juni 2021",
    Genre : "K-Pop, R&B, Ballad",
    Bahasa : "Korea, Mandarin",
    Durasi : "17:11",
  },
];